apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/melihekmekci1/dream.git'
    path: k8s/gitops
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
