apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: example-validating-webhook
webhooks:
  - name: example.webhook.com
    clientConfig:
      service:
        name: webhook-server
        namespace: default
        path: "/validate"
        # Assuming the Kubernetes cluster and the webhook service are in the same namespace.
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURmakNDQW1hZ0F3SUJBZ0lVSnkrLy9uczdDK2ttdXN0dG1MZzFQaENVdEFJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FkMlZpYUc5dmF5MXpaWEoyWlhJdVpHVm1ZWFZzZEM1emRtTXdIaGNOTWpRdwpOREV6TVRRd05UVXlXaGNOTWpVd05ERXpNVFF3TlRVeVdqQWxNU013SVFZRFZRUUREQnAzWldKb2IyOXJMWE5sCmNuWmxjaTVrWldaaGRXeDBMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUsveFhsbjVMNDBWWHFpZmtWYUFUT25FTEpWRFdud1pGWU5ZeC9jR1ptRUJnSXFMN09BT0Jxd3lCYWtCRVd4ego1cmlONnN3QXhYNlpINFdaU0ZNWXdqSkhoWS8rZmtTcHhsbjdyV1Z4aVFiL29DejBwdGJ6VjRLVEltSzA0UkxBClh6bFVtUVhzaHBzdFdZRFVwcXpVWHlXRDVkWnVmNDBibHNEVnF4YVRJZ3c1b2d2WDBEMGhUZklmSTg2K0FSZ2kKWkdCSE82cTVXcFlTdTBnSVptY0E3bFY5dDVRVVMxTUZ4L1c4R0dVY2ozalJZcTNXWjBsMk1mZTRFRVczT2F3TAo0NmkwdElnN1lkaFUveEU3VHNqZk5nMU5kQ2xBbFlRdGNVK0dLb0ZLNWtiZEZzODkvaXZDZEVJR2c2TnIwT1cyCnNDUk90YzdlWGZDbFBaT0FhdFBScnZjQ0F3RUFBYU9CcFRDQm9qQWRCZ05WSFE0RUZnUVUrWGtUUmZSWUIwM3gKMnQvaWV0VWorVGdwTUg4d0h3WURWUjBqQkJnd0ZvQVUrWGtUUmZSWUIwM3gydC9pZXRVaitUZ3BNSDh3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pCUEJnTlZIUkVFU0RCR2docDNaV0pvYjI5ckxYTmxjblpsY2k1a1pXWmhkV3gwCkxuTjJZNElvZDJWaWFHOXZheTF6WlhKMlpYSXVaR1ZtWVhWc2RDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZFpIM2daRTcyNFJVbHJyZGRoclR6VjR6SDB4dmtySGhsUzNMczJOZgpoZHdxT0l1cDlGaGpYUVJNRUd6ZTgyQS9ZQU83TkluNTlJeDMzZ1FYcWJFbGozQ3dEZEZJTlFOTVRPYlNrQ0hTCkphdDVySlFJN1hRbktjNDFndU5SelRhQW0yUEdzUmhGcFZqaEdJM1pPLysycU1XMHJ4NmwwUzRoSXBER21ybkMKNlhSNktRcEFOWS9yU0FZK2lGQVZkbGNYU2NaSjhEc3dUSTlRTWFtN1dnaUNTb0luU3ZOMVRwNHFXQjJyeWRUMAo2WGlCbEpRTVB6dDZYY2xxQldtTzI4V2xFM3ljWW9pMGZyVEhxR1I4ZWtFTnZFak5mekRidWZKOTlsTkJpN1htCmpMV1NPYlZ5WnZqNEE4QXk5UHpRMmZJWTdiZHI0VGFHeWVibEM2ZDlDcS9SVnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps", "extensions"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
